#!/bin/bash

#$ -M drichte2@nd.edu
#$ -m n
#$ -pe mpi-16 64
# #$ -q *@@richter
#$ -q gpu@qa-xp-011,gpu@d8civy053,gpu@d8civy054,gpu@d8civy059
#$ -N reid
#$ -j y

case=case0
time=0000000
runout=$case.out.$time

datadir=/scratch365/drichte2/reid/$case
homedir=~/Research/reid/$case

cd $homedir

module load mvapich2/2.1-intel-15.0-mlx
module load intel/15.0

imachine=0
echo $imachine > ./mach.file
echo $datadir >> ./mach.file

mpirun -n 64 ../build/lesmpi.a $homedir/params.in > $datadir/$runout


